### ISSUE TITLE
Chicagofier doesn't depend on python3-gi

### ISSUE THREAD

**Issue by Tablecloth39** [dominichayesferen/Chicagofier#5]
Traceback (most recent call last):
File "/tmp/ChicagoStuff11288/Chicago95/./installer.py", line 3, in <module>
import gi
ModuleNotFoundError: No module named 'gi' 

I installed Python gi and ran the script again, but the issue persists.

**Comment by dominichayesferen** [comment]
sudo apt install python3-gi

**Comment by Tablecloth39** [comment]
I tried that and pip install gi and PyGobjects. I still get the same issue

**Comment by FennekFox19** [comment]
> Traceback (most recent call last): File "/tmp/ChicagoStuff11288/Chicago95/./installer.py", line 3, in import gi ModuleNotFoundError: No module named 'gi'
> 
> I installed Python gi and ran the script again, but the issue persists.

What Xubuntu version were you using back then?
